DECLARE
 VEZES NUMBER := 0;
 INICIO NUMBER := '&INICIO';
 FIM NUMBER := '&FIM';
 MSG VARCHAR2(200);
 BEGIN
 FOR I IN INICIO..FIM LOOP
 VEZES := VEZES + 1;
 END LOOP;
 FOR I IN FIM..INICIO LOOP
 VEZES := VEZES + 1;
 END LOOP;
 FOR I IN REVERSE INICIO..FIM LOOP
 MSG := MSG ||I||' ';
 END LOOP;
 dbms_output.PUT_LINE('O valor de VEZES é '|| VEZES);
 END;